import type { AnimMeta, FxMeta } from './types';

export const animations: AnimMeta[] = [
  { name: 'fade-up', label: 'Fade Up', category: 'fade', description: '从下方淡入' },
  { name: 'fade-down', label: 'Fade Down', category: 'fade', description: '从上方淡入' },
  { name: 'fade-left', label: 'Fade Left', category: 'fade', description: '从右侧淡入' },
  { name: 'fade-right', label: 'Fade Right', category: 'fade', description: '从左侧淡入' },
  { name: 'rise-in', label: 'Rise In', category: 'fade', description: '从底部升起' },
  { name: 'zoom-pop', label: 'Zoom Pop', category: 'scale', description: '缩放弹入' },
  { name: 'blur-in', label: 'Blur In', category: 'scale', description: '模糊淡入' },
  { name: 'flip-in', label: 'Flip In', category: '3d', description: '3D 翻转入场' },
  { name: 'rotate-in', label: 'Rotate In', category: '3d', description: '旋转入场' },
  { name: 'slide-up', label: 'Slide Up', category: 'slide', description: '从底部滑入' },
  { name: 'slide-left', label: 'Slide Left', category: 'slide', description: '从右侧滑入' },
  { name: 'glitch-in', label: 'Glitch In', category: 'effect', description: '故障风入场' },
  { name: 'typewriter', label: 'Typewriter', category: 'effect', description: '打字机效果' },
  { name: 'clip-in', label: 'Clip In', category: 'effect', description: '裁剪入场' },
  { name: 'draw-in', label: 'Draw In', category: 'effect', description: '描边绘制入场' },
  { name: 'bounce-in', label: 'Bounce In', category: 'scale', description: '弹跳入场' },
  { name: 'elastic-in', label: 'Elastic In', category: 'scale', description: '弹性入场' },
  { name: 'swing-in', label: 'Swing In', category: '3d', description: '摇摆入场' },
  { name: 'drop-in', label: 'Drop In', category: 'slide', description: '从顶部掉落' },
  { name: 'unfold-in', label: 'Unfold In', category: '3d', description: '展开入场' },
  { name: 'wipe-in', label: 'Wipe In', category: 'effect', description: '擦除入场' },
  { name: 'spin-in', label: 'Spin In', category: '3d', description: '旋转缩小入场' },
  { name: 'shutter-in', label: 'Shutter In', category: 'effect', description: '百叶窗入场' },
  { name: 'split-in', label: 'Split In', category: 'effect', description: '分裂入场' },
  { name: 'roll-in', label: 'Roll In', category: 'slide', description: '滚入' },
  { name: 'expand-in', label: 'Expand In', category: 'scale', description: '扩展入场' },
  { name: 'shake-in', label: 'Shake In', category: 'effect', description: '抖动入场' },
];

export const fxList: FxMeta[] = [
  { name: 'particle-burst', label: '粒子爆发', description: '粒子从中心向外扩散' },
  { name: 'confetti-cannon', label: '彩纸炮', description: '五彩纸屑飘落' },
  { name: 'firework', label: '烟花', description: '烟花绽放效果' },
  { name: 'starfield', label: '星场', description: '星空穿越效果' },
  { name: 'matrix-rain', label: '矩阵雨', description: 'Matrix 数字雨' },
  { name: 'knowledge-graph', label: '知识图谱', description: '力导向图节点动画' },
  { name: 'neural-net', label: '神经网络', description: '脉冲连接动画' },
  { name: 'constellation', label: '星座', description: '星座连线效果' },
  { name: 'orbit-ring', label: '轨道环', description: '环形轨道运动' },
  { name: 'galaxy-swirl', label: '银河漩涡', description: '银河旋转效果' },
  { name: 'word-cascade', label: '文字瀑布', description: '文字从上方飘落' },
  { name: 'letter-explode', label: '字母爆炸', description: '字母碎片飞散' },
  { name: 'chain-react', label: '链式反应', description: '节点链式激活' },
  { name: 'magnetic-field', label: '磁场', description: '磁力线效果' },
  { name: 'data-stream', label: '数据流', description: '数据流粒子效果' },
  { name: 'gradient-blob', label: '渐变气泡', description: '流动渐变气泡' },
  { name: 'sparkle-trail', label: '闪光轨迹', description: '闪烁尾迹效果' },
  { name: 'shockwave', label: '冲击波', description: '冲击波扩散效果' },
  { name: 'typewriter-multi', label: '多行打字', description: '多行打字机效果' },
  { name: 'counter-explosion', label: '数字爆炸', description: '数字碎片飞散' },
];